In [1]:
import tensorflow as tf

In [4]:
model = tf.keras.models.load_model('sentiment_model')

Metal device set to: Apple M1


2023-02-23 13:25:07.848345: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-02-23 13:25:07.848463: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [5]:
from transformers import BertTokenizer

In [6]:
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

In [7]:
### function that will prepare our data

def prep_data(text):
    tokens = tokenizer(text, max_length=512, truncation=True,
                      padding='max_length', add_special_tokens=True, return_tensors='tf')
    return {'input_ids': tokens['input_ids'], 'attention_mask': tokens['attention_mask']}

In [8]:
prep_data('hello world')

{'input_ids': <tf.Tensor: shape=(1, 512), dtype=int32, numpy=
 array([[  101, 19082,  1362,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
  

In [19]:
model.predict(prep_data('this movie was terrible'))

1/1 [==============================] - 0s 246ms/step


array([[0.01492799, 0.26910788, 0.6693806 , 0.02495269, 0.0216309 ]],
      dtype=float32)

In [20]:
probs = model.predict(prep_data('this movie was terrible'))[0]
probs

1/1 [==============================] - 0s 245ms/step


array([0.01492799, 0.26910788, 0.6693806 , 0.02495269, 0.0216309 ],
      dtype=float32)

In [21]:
import numpy as np

In [22]:
np.argmax(probs)

2

In [23]:
# my model is f bad

In [26]:
import pandas as pd


In [42]:
pd.set_option('display.max_colwidth', None)

In [36]:
pwd

'/Users/saramaras/Documents/github/NLP_Transformers_Python/code/project_build_tf_sentiment_model'

In [51]:
df = pd.read_csv('./data/test.tsv', sep='\t')
df.shape()

TypeError: 'tuple' object is not callable

In [45]:
df = df.drop_duplicates(subset=['SentenceId'], keep='first')

In [46]:
df.head()

PhraseId  SentenceId  \
0      156061        8545   
15     156076        8546   
93     156154        8547   
117    156178        8548   
158    156219        8549   

                                                                                                                                                                                                                                              Phrase  
0                                                                                                                                                                                             An intermittently pleasing but mostly routine effort .  
15   Kidman is really the only thing that 's worth watching in Birthday Girl , a film by the stage-trained Jez Butterworth -LRB- Mojo -RRB- that serves as yet another example of the sad decline of British comedies in the post-Full Monty world .  
93                                                                                                                                                                           Once you get into its rhythm ... the movie becomes a heady experience .  
117                                                                                                 I kept wishing I was watching a documentary about the wartime Navajos and what they accomplished instead of all this specious Hollywood hoo-ha .  
158                                                                                                                                          Kinnear does n't aim for our sympathy , but rather delivers a performance of striking skill and depth .

In [47]:
df['Sentiment'] = None

In [50]:
for i, row in df.iterrows():
    token = prep_data(row['Phrase'])
    probs = model.predict(token)
    pred = np.argmax(probs)
    df.at[i, 'Sentiment'] = pred
    

1/1 [==============================] - 0s 236ms/step


1/1 [==============================] - 0s 214ms/step


1/1 [==============================] - 0s 212ms/step


1/1 [==============================] - 0s 215ms/step


1/1 [==============================] - 0s 216ms/step


1/1 [==============================] - 0s 216ms/step


1/1 [==============================] - 0s 201ms/step


1/1 [==============================] - 0s 223ms/step


1/1 [==============================] - 0s 211ms/step


1/1 [==============================] - 0s 206ms/step


1/1 [==============================] - 0s 236ms/step


1/1 [==============================] - 0s 209ms/step


1/1 [==============================] - 0s 208ms/step


1/1 [==============================] - 0s 207ms/step


1/1 [==============================] - 0s 211ms/step


1/1 [==============================] - 0s 210ms/step


1/1 [==============================] - 0s 211ms/step


1/1 [==============================] - 0s 198ms/step


1/1 [==============================] - 0s 210ms/step


1/1 [==============================] - 0s 208ms/step


1/1 [==============================] - 0s 219ms/step


1/1 [==============================] - 0s 231ms/step
